### ISSUE TITLE
Failed to init autograder server

### ISSUE THREAD

**Issue by xuantengh** [howardlau1999/autograder-server#1]
According to the docs, I download the binary file from the release page, and then run:
```
./autograder-server --init --email email@mail.com
panic: Config File "config" Not Found in "[/etc/autograder-server /mnt/sda/user/.autograder-server /mnt/user/autograder]"

goroutine 1 [running]:
main.serverReadConfig()
        /home/runner/work/autograder-server/autograder-server/cmd/autograder_server.go:171 +0x393
main.main()
        /home/runner/work/autograder-server/autograder-server/cmd/autograder_server.go:268 +0xbc
```

If I try to generate the config first `./autograder-server --config`, there is still same errors above.

IIUC, it seems that the `serverReadConfig()` function is called before `processCommandLineOptions()`?
https://github.com/howardlau1999/autograder-server/blob/b1057e8e906585f2735efc4b895347c0c089d278/cmd/autograder_server.go#L277-L286

**Comment by howardlau1999** [comment]
fixed

**Comment by tengyangzh** [comment]
> fixed

It seems that the problems still occur when I use the latest release version.
Could you help me to check whether the binary works well? Thanks.
